import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { getRuntimeConfig } from "../src/config.js";
import { startSwitchboardRuntime } from "../src/runtime.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const INSTALLER = path.join(ROOT, "scripts", "install-opencode-plugin.js");

test("OpenCode installer embeds absolute bridge paths and is idempotent", () => {
  const temporary = mkdtempSync(path.join(tmpdir(), "agent-switchboard-opencode-"));
  try {
    const env = { ...process.env, XDG_CONFIG_HOME: temporary };
    const first = spawnSync(process.execPath, [INSTALLER], { cwd: ROOT, env, encoding: "utf8" });
    assert.equal(first.status, 0, first.stderr);

    const target = path.join(temporary, "opencode", "plugins", "switchboard.js");
    const installed = readFileSync(target, "utf8");
    assert.match(installed, /Generated by the Agent Switchboard OpenCode installer/);
    assert.equal(installed.includes(`const bridgeCommand = ${JSON.stringify(process.execPath)};`), true);
    assert.equal(installed.includes(path.join(ROOT, "src", "bin", "switchboardctl.js")), true);
    assert.equal(installed.includes('"opencode", "--stream"'), true);
    assert.equal(installed.includes('const bridgeCommand = "switchboardctl";'), false);

    const syntax = spawnSync(process.execPath, ["--check", target], { encoding: "utf8" });
    assert.equal(syntax.status, 0, syntax.stderr);

    const second = spawnSync(process.execPath, [INSTALLER], { cwd: ROOT, env, encoding: "utf8" });
    assert.equal(second.status, 0, second.stderr);
    assert.match(second.stdout, /already installed/);
  } finally {
    rmSync(temporary, { recursive: true, force: true });
  }
});

test("installed OpenCode plugin delivers explicit prompt lifecycle events", async () => {
  const temporary = mkdtempSync(path.join(tmpdir(), "agent-switchboard-opencode-events-"));
  let runtime;
  let hooks;
  let nestedHooks;
  const previous = {
    home: process.env.SWITCHBOARD_HOME,
    host: process.env.SWITCHBOARD_HOST,
    port: process.env.SWITCHBOARD_PORT,
    debug: process.env.SWITCHBOARD_DEBUG,
    nested: process.env.AGENT_SWITCHBOARD_CHILD,
    tmux: process.env.TMUX,
  };
  try {
    delete process.env.AGENT_SWITCHBOARD_CHILD;
    delete process.env.TMUX;
    const configHome = path.join(temporary, "config");
    const stateHome = path.join(temporary, "state");
    const installed = spawnSync(process.execPath, [INSTALLER], {
      cwd: ROOT,
      env: { ...process.env, XDG_CONFIG_HOME: configHome },
      encoding: "utf8",
    });
    assert.equal(installed.status, 0, installed.stderr);

    const config = {
      ...getRuntimeConfig({ ...process.env, SWITCHBOARD_HOME: stateHome, SWITCHBOARD_PORT: "43117" }),
      port: 0,
    };
    runtime = await startSwitchboardRuntime({ config, discovery: false, logger: { error() {} } });
    const port = runtime.service.server.address().port;
    process.env.SWITCHBOARD_HOME = stateHome;
    process.env.SWITCHBOARD_HOST = "127.0.0.1";
    process.env.SWITCHBOARD_PORT = String(port);
    process.env.SWITCHBOARD_DEBUG = "1";

    const direct = await runCommand(
      process.execPath,
      [path.join(ROOT, "src", "bin", "switchboardctl.js"), "emit", "--harness", "opencode", "--strict"],
      JSON.stringify({
        id: "event-direct",
        type: "permission.asked",
        properties: { sessionID: "direct-e2e", id: "permission-direct" },
      }),
    );
    assert.equal(direct.code, 0, direct.stderr);
    await waitForSession(runtime, "direct-e2e", "needs_attention");

    const pluginPath = path.join(configHome, "opencode", "plugins", "switchboard.js");
    const pluginSource = readFileSync(pluginPath, "utf8");
    const pluginModule = await import(`data:text/javascript;base64,${Buffer.from(pluginSource).toString("base64")}`);
    const pendingPermissions = [];
    const pendingQuestions = [];
    const client = {
      permission: { list: async () => ({ data: [...pendingPermissions] }) },
      question: { list: async () => ({ data: [...pendingQuestions] }) },
    };
    hooks = await pluginModule.AgentSwitchboard({ client, directory: ROOT });
    const shellEnvironment = { env: {} };
    await hooks["shell.env"]({ sessionID: "plugin-e2e" }, shellEnvironment);
    assert.equal(shellEnvironment.env.AGENT_SWITCHBOARD_CHILD, "1");

    await hooks.event({
      event: {
        id: "event-needs-input",
        type: "permission.asked",
        properties: { sessionID: "plugin-e2e", id: "permission-e2e", patterns: ["private"] },
      },
    });
    const attention = await waitForSession(runtime, "plugin-e2e", "needs_attention");
    assert.equal(attention.attentionRequestId, "permission-e2e");

    await hooks.event({
      event: {
        id: "event-input-resolved",
        type: "permission.replied",
        properties: { sessionID: "plugin-e2e", requestID: "permission-e2e" },
      },
    });
    await waitForSession(runtime, "plugin-e2e", "working");

    const detail = runtime.store.getSessionDetail(attention.id);
    assert.equal(JSON.stringify(detail).includes("private"), false);

    pendingPermissions.push({
      id: "permission-external-directory",
      sessionID: "plugin-recovered-permission",
      permission: "external_directory",
      patterns: ["/home/example/.config/systemd/user/*"],
    });
    const recoveredPermission = await waitForSession(
      runtime,
      "plugin-recovered-permission",
      "needs_attention",
    );
    assert.equal(recoveredPermission.attentionRequestId, "permission-external-directory");

    pendingQuestions.push({
      id: "question-preference",
      sessionID: "plugin-recovered-question",
      questions: [
        {
          header: "Preference",
          question: "Choose the private deployment preference",
          options: [{ label: "Private choice", description: "Sensitive detail" }],
        },
      ],
    });
    const recoveredQuestion = await waitForSession(
      runtime,
      "plugin-recovered-question",
      "needs_attention",
    );
    assert.equal(recoveredQuestion.attentionRequestId, "question-preference");

    const recoveredDetails = [recoveredPermission, recoveredQuestion].map((session) =>
      JSON.stringify(runtime.store.getSessionDetail(session.id)),
    );
    assert.equal(recoveredDetails.some((detailValue) => detailValue.includes("systemd/user")), false);
    assert.equal(recoveredDetails.some((detailValue) => detailValue.includes("Private choice")), false);

    pendingPermissions.length = 0;
    pendingQuestions.length = 0;
    await waitForSession(runtime, "plugin-recovered-permission", "working");
    await waitForSession(runtime, "plugin-recovered-question", "working");

    process.env.AGENT_SWITCHBOARD_CHILD = "1";
    nestedHooks = await pluginModule.AgentSwitchboard({ client: {}, directory: ROOT });
    await nestedHooks.event({
      event: {
        id: "event-nested",
        type: "permission.asked",
        properties: { sessionID: "nested-e2e", id: "permission-nested" },
      },
    });
    await new Promise((resolve) => setTimeout(resolve, 150));
    assert.equal(
      runtime.store.getSnapshot().sessions.some((item) => item.nativeSessionId === "nested-e2e"),
      false,
    );
  } finally {
    await nestedHooks?.dispose?.();
    await hooks?.dispose?.();
    await runtime?.stop();
    restoreEnvironment("SWITCHBOARD_HOME", previous.home);
    restoreEnvironment("SWITCHBOARD_HOST", previous.host);
    restoreEnvironment("SWITCHBOARD_PORT", previous.port);
    restoreEnvironment("SWITCHBOARD_DEBUG", previous.debug);
    restoreEnvironment("AGENT_SWITCHBOARD_CHILD", previous.nested);
    restoreEnvironment("TMUX", previous.tmux);
    rmSync(temporary, { recursive: true, force: true });
  }
});

async function waitForSession(runtime, nativeSessionId, primaryState) {
  const deadline = Date.now() + 3000;
  while (Date.now() < deadline) {
    const session = runtime.store
      .getSnapshot()
      .sessions.find((item) => item.nativeSessionId === nativeSessionId);
    if (session?.primaryState === primaryState) return session;
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  assert.fail(
    `Timed out waiting for ${nativeSessionId} to become ${primaryState}: ${JSON.stringify(runtime.store.getSnapshot())}`,
  );
}

function restoreEnvironment(name, value) {
  if (value === undefined) delete process.env[name];
  else process.env[name] = value;
}

function runCommand(command, args, input) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: ROOT,
      env: process.env,
      stdio: ["pipe", "ignore", "pipe"],
    });
    let stderr = "";
    child.stderr.setEncoding("utf8");
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("exit", (code) => resolve({ code, stderr }));
    child.stdin.end(input);
  });
}
