#!/usr/bin/env node

import { existsSync, lstatSync, readFileSync } from "node:fs";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { installHarnessHooks, resolveSetupPaths } from "./harness-hooks.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rawArgs = process.argv.slice(2);
const args = new Set(rawArgs);
const dryRun = args.has("--dry-run");
const autostart = args.has("--autostart");
const noLaunch = args.has("--no-launch");
const skipGnome = args.has("--skip-gnome");
const skipHooks = args.has("--skip-hooks");
const paths = resolveSetupPaths();
const allowedArgs = new Set(["--autostart", "--dry-run", "--help", "--no-launch", "--skip-gnome", "--skip-hooks"]);

function usage() {
  return `Agent Switchboard setup

Usage: npm run setup -- [options]

  --autostart    start the desktop pane after login
  --dry-run      report intended changes without writing or launching
  --no-launch    finish setup without opening the desktop pane
  --skip-gnome   do not install the GNOME desktop connector
  --skip-hooks   do not install Codex, Claude Code, or OpenCode events
`;
}

function runtimeSupported(version = process.versions.node) {
  const [major, minor] = version.split(".").map((value) => Number.parseInt(value, 10));
  return major > 22 || (major === 22 && minor >= 5);
}

function executableOnPath(name) {
  for (const directory of String(process.env.PATH || "").split(path.delimiter)) {
    if (!directory) continue;
    const candidate = path.join(directory, name);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function isGnomeDesktop() {
  const desktop = `${process.env.XDG_CURRENT_DESKTOP || ""}:${process.env.DESKTOP_SESSION || ""}`;
  return /gnome|ubuntu/i.test(desktop);
}

function gnomeConnectorPlan() {
  if (skipGnome) return { install: false, message: "skipped by --skip-gnome" };
  if (process.platform !== "linux" || !isGnomeDesktop()) {
    return { install: false, message: "skipped: this is not an active GNOME Linux desktop" };
  }
  const shell = executableOnPath("gnome-shell");
  const extensions = executableOnPath("gnome-extensions");
  if (!shell || !extensions) {
    return { install: false, message: "skipped: GNOME extension tools are unavailable" };
  }
  const version = spawnSync(shell, ["--version"], { encoding: "utf8" });
  const description = String(version.stdout || version.stderr || "GNOME Shell").trim();
  if (version.status !== 0 || !/GNOME Shell (42|43|44)\b/.test(description)) {
    return {
      install: false,
      message: `skipped: ${description || "this GNOME version"} is not supported by the bundled connector`,
    };
  }
  return { install: true, message: description };
}

function assertOwnedRegularFile(target, label, owns) {
  if (!existsSync(target)) return;
  const metadata = lstatSync(target);
  if (metadata.isSymbolicLink() || !metadata.isFile()) {
    throw new Error(`${label} destination ${target} is not a regular Switchboard-owned file; it was left unchanged.`);
  }
  if (!owns(readFileSync(target, "utf8"))) {
    throw new Error(`${label} destination ${target} belongs to something else; it was left unchanged.`);
  }
}

function preflightDestinations(gnome) {
  if (!skipHooks) {
    installHarnessHooks({ root: ROOT, dryRun: true });
    assertOwnedRegularFile(
      paths.openCodePlugin,
      "OpenCode plugin",
      (content) =>
        content.startsWith("// Generated by the Agent Switchboard OpenCode installer.") ||
        content.includes("Agent Switchboard OpenCode integration"),
    );
  }
  const desktopOwned = (content) =>
    content.includes("X-Agent-Switchboard-Owned=true") ||
    (content.includes("Name=Agent Switchboard") && content.includes("StartupWMClass=agent-switchboard"));
  assertOwnedRegularFile(paths.desktopLauncher, "Desktop launcher", desktopOwned);
  if (autostart) assertOwnedRegularFile(paths.autostartLauncher, "Login autostart", desktopOwned);

  if (gnome.install && existsSync(paths.gnomeExtension)) {
    const metadata = lstatSync(paths.gnomeExtension);
    if (metadata.isSymbolicLink() || !metadata.isDirectory()) {
      throw new Error(`GNOME connector destination ${paths.gnomeExtension} is not a Switchboard-owned directory; it was left unchanged.`);
    }
    let extension;
    try {
      extension = JSON.parse(readFileSync(path.join(paths.gnomeExtension, "metadata.json"), "utf8"));
    } catch (error) {
      throw new Error(`GNOME connector destination ${paths.gnomeExtension} could not be verified; it was left unchanged (${error.message}).`);
    }
    if (extension.uuid !== "agent-switchboard@skylabs-ai.com") {
      throw new Error(`GNOME connector destination ${paths.gnomeExtension} belongs to another extension; it was left unchanged.`);
    }
  }
}

function runNodeScript(relativePath, scriptArgs = []) {
  const script = path.join(ROOT, relativePath);
  const result = spawnSync(process.execPath, [script, ...scriptArgs], {
    cwd: ROOT,
    env: process.env,
    encoding: "utf8",
  });
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.status !== 0) {
    const detail = String(result.stderr || result.stdout || "").trim();
    throw new Error(detail || `${relativePath} exited with status ${result.status}`);
  }
}

function heading(label) {
  process.stdout.write(`\n${label}\n`);
}

function printHookResult(result) {
  for (const integration of result.integrations) {
    const verb = integration.changed ? (dryRun ? "would update" : "updated") : "already ready";
    process.stdout.write(`  ${integration.harness.padEnd(7)} ${verb}: ${integration.path}\n`);
  }
}

function launchDesktop() {
  const runner = path.join(ROOT, "scripts", "run-desktop.js");
  const child = spawn(process.execPath, [runner], {
    cwd: ROOT,
    env: process.env,
    detached: true,
    stdio: "ignore",
  });
  child.unref();
}

async function main() {
  if (args.has("--help")) {
    process.stdout.write(usage());
    return;
  }
  const unknown = rawArgs.find((argument) => !allowedArgs.has(argument));
  if (unknown) throw new Error(`Unknown option: ${unknown}\n\n${usage()}`);
  if (!runtimeSupported()) {
    throw new Error(`Node.js 22.5 or newer is required; found ${process.versions.node}.`);
  }
  if (!existsSync(path.join(ROOT, "node_modules", ".bin", "electron"))) {
    throw new Error("Dependencies are missing. Run npm ci before npm run setup.");
  }
  const gnome = gnomeConnectorPlan();
  preflightDestinations(gnome);

  process.stdout.write(`Agent Switchboard setup${dryRun ? " (dry run)" : ""}\n`);
  process.stdout.write(`Checkout: ${ROOT}\n`);

  if (!skipHooks) {
    heading("Harness integrations");
    printHookResult(installHarnessHooks({ root: ROOT, dryRun }));

    if (dryRun) process.stdout.write(`  opencode would update: ${paths.openCodePlugin}\n`);
    else runNodeScript("scripts/install-opencode-plugin.js");
  } else {
    heading("Harness integrations");
    process.stdout.write("  skipped by --skip-hooks\n");
  }

  heading("Desktop launcher");
  if (dryRun) {
    process.stdout.write(`  would install: ${paths.desktopLauncher}\n`);
    if (autostart) process.stdout.write(`  would enable at login: ${paths.autostartLauncher}\n`);
  } else {
    runNodeScript("scripts/install-desktop.js", autostart ? ["--autostart"] : []);
  }

  heading("GNOME desktop connector");
  if (!gnome.install) {
    process.stdout.write(`  ${gnome.message}\n`);
  } else if (dryRun) {
    process.stdout.write(`  would install: ${paths.gnomeExtension}\n`);
  } else {
    runNodeScript("scripts/install-gnome-extension.js");
  }

  heading("Verification");
  if (dryRun) {
    process.stdout.write("  would run switchboardctl doctor\n");
  } else {
    runNodeScript("src/bin/switchboardctl.js", ["doctor"]);
  }

  const graphical = Boolean(process.env.DISPLAY || process.env.WAYLAND_DISPLAY);
  if (!dryRun && !noLaunch && graphical) {
    launchDesktop();
    process.stdout.write("\nStarted Agent Switchboard.\n");
  } else if (!dryRun && !noLaunch) {
    process.stdout.write("\nSetup is complete. Open Agent Switchboard from the application menu on your desktop.\n");
  } else if (!dryRun) {
    process.stdout.write("\nSetup is complete. Run npm run gui when you are ready.\n");
  }

  if (!dryRun && !skipHooks) {
    process.stdout.write("Restart any Codex, Claude Code, or OpenCode sessions that were already running.\n");
    process.stdout.write("In Codex, open /hooks once to review and trust the new user hooks.\n");
  }
  if (!dryRun && gnome.install) {
    process.stdout.write("If GNOME reports the connector as pending, log out and back in once.\n");
  }
}

main().catch((error) => {
  process.stderr.write(`Setup stopped safely: ${error.message}\n`);
  process.exitCode = 1;
});
